name: Docker Go

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and run app image, then wait for 30 seconds
      run: docker compose up --build -d app & sleep 30
    - name: Send ping request and check response
      run: |
        response=$(curl --write-out "%{http_code}" --silent --output /dev/null http://localhost:8080/ping)
        if [ "$response" -ne 200 ]; then
          echo "API did not respond with HTTP 200, response was $response"
          exit 1
        fi
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'
    - name: Install dependencies
      run: go mod download
    - name: Run tests
      run: go test -v ./...
    - name: Stop and remove containers
      run: docker compose down
