name: Docker Go

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and run app image in background
      run: docker compose up --build -d app
    - name: Send ping request and check response
      run: |
        sleep 180
        curl -v http://localhost:8080/ping
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'
    - name: Install dependencies
      run: go mod download
    - name: Run tests
      run: go test -v ./...
    - name: Stop and remove containers
      run: docker compose down
